"""Minutes-of-Meeting rendering."""

from __future__ import annotations

import re
from datetime import datetime
from pathlib import Path

from ..models import MeetingSummary


def _slug(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")[:60]
    return slug or "meeting"


def render_mom(summary: MeetingSummary) -> str:
    """Render a MeetingSummary as a Markdown Minutes-of-Meeting document."""
    L: list[str] = []
    L.append("# Minutes of Meeting\n")
    L.append("| | |")
    L.append("|---|---|")
    L.append(f"| **Title** | {summary.title} |")
    L.append(f"| **Date** | {summary.date} |")
    L.append(f"| **Attendees** | {', '.join(summary.attendees) if summary.attendees else '*not captured*'} |")
    L.append("")
    L.append("## Executive Summary")
    L.append(summary.executive_summary or "_No summary available._")
    L.append("")

    if summary.key_topics:
        L.append("## Key Topics")
        L.extend(f"- {t}" for t in summary.key_topics)
        L.append("")

    if summary.discussion_points:
        L.append("## Discussion")
        for dp in summary.discussion_points:
            L.append(f"### {dp.topic or 'Discussion'}")
            L.append(dp.summary or "_No detail captured._")
            L.append("")

    if summary.decisions:
        L.append("## Decisions")
        L.extend(f"- {d}" for d in summary.decisions)
        L.append("")

    L.append("## Action Items")
    if summary.action_items:
        L.append("| # | Task | Owner | Due |")
        L.append("|---|------|-------|-----|")
        for i, item in enumerate(summary.action_items, 1):
            task = item.task.replace("|", "\\|")
            L.append(f"| {i} | {task} | {item.owner or '-'} | {item.due or '-'} |")
    else:
        L.append("_No action items captured._")
    L.append("")

    if summary.open_questions:
        L.append("## Open Questions / Risks")
        L.extend(f"- {q}" for q in summary.open_questions)
        L.append("")

    if summary.next_steps:
        L.append("## Next Steps")
        L.extend(f"- {s}" for s in summary.next_steps)
        L.append("")

    L.append("---")
    L.append("_Generated by Meeting Agent._")
    return "\n".join(L) + "\n"


def save_mom(summary: MeetingSummary, output_dir: str | Path, title: str | None = None) -> Path:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    name = title or summary.title
    filename = f"MOM_{datetime.now().strftime('%Y%m%d_%H%M%S')}_{_slug(name)}.md"
    path = out / filename
    path.write_text(render_mom(summary), encoding="utf-8")
    return path
